### ISSUE TITLE
tslint should not be a second step in `Setting up, building and running` instructions

### ISSUE THREAD

**Issue by mkuzak** [nlesc-sherlock/punchcardjs#29]
README.md (in `testing` branch) tells the user to run `tslint` after cloning the repository. In my opinion it should be removed from there for the following resons:
- the code that is committed should be already linted by the person who made the changes
- the person who wants to run / use the code should not be responsible for linting someone's changes
- the linter will only tell the user if there are issues or not with the code but will not help him/her to run anything
- if linting is the necessary step before `tsc`, there should be separate task that does `tslint && tsc`

**Comment by jspaaks** [comment]
perhaps we could add `npm run tslint && npm run csslint` to `npm run predist` [here](https://github.com/nlesc-sherlock/punchcardjs/blob/971aa8f0c03785d48784faa4783e2cf7c530e3af/package.json#L26)?

and [this](https://github.com/nlesc-sherlock/punchcardjs/blob/971aa8f0c03785d48784faa4783e2cf7c530e3af/package.json#L25) would need to be 

```
"precover": "trash sites/coverage/ && npm run jslint && npm run jshint && npm run dist"
```

instead of 

```
"precover": "trash sites/coverage/ && npm run lint && npm run dist"
```

**Comment by jspaaks** [comment]
I've made the proposed changed in 9b60b6c13665ac2e90e98820ffee8916f304e08f. closing.
